# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build bedtools-ng

# Events that trigger workflow
on:
  push:
    branches: [ main, solutions-006 ]
    # Only files matching the following glob expressions will trigger the workflow
    # (e.g. changes to the README will not trigger the workflow)
    paths:
      - "bedtools_ng/**"
      - "data/**"
      - ".github/workflows/build-bedtools-ng.yml"
      - ".gitignore"
      - ".pyproject.yaml"
      - "setup.*"

  pull_request:
    branches: [ main, solutions-006 ]
    paths:
      - "bedtools_ng/**"
      - "data/**"
      - ".github/workflows/build-bedtools-ng.yml"
      - ".gitignore"
      - ".pyproject.yaml"
      - "setup.*"

# Define jobs
jobs:
  # Name first job
  build-bedtools-ng:
    # Pick the OS where the workflow will be run
    runs-on: ubuntu-latest

    # Define one of more steps
    steps:
      # Use an action to checkout the current repository
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git                \
                                  python3            \
                                  python3-pip        \
                                  python3-venv       \
                                  python3-setuptools

      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: |
             venv
          key: venv-cache-${{ hashFiles('setup.cfg', 'setup.py', 'pyproject.toml') }}

      - name: Create venv
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: python3 -m venv ./venv

      - name: Install bedtools-ng
        run: venv/bin/pip install '.[all]'

      - name: Run unit tests
        run: venv/bin/pytest .

      - name: Run bedtools-ng
        run: |
          venv/bin/bedtools-ng --help
          venv/bin/bedtools-ng --version
          
          venv/bin/bedtools-ng count-overlaps  \
                               data/chroms.bed \
                               data/grch38_transcripts.bed
