# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build bedtools-ng

# Events that trigger workflow
on:
  push:
    branches: [ main, solutions-005 ]
    # Only files matching the following glob expressions will trigger the workflow
    # (e.g. changes to the README will not trigger the workflow)
    paths:
      - "bedtools_ng/**"
      - "data/**"
      - ".github/workflows/build-bedtools-ng.yml"
      - ".gitignore"
      - ".pyproject.yaml"
      - "setup.*"

  pull_request:
    branches: [ main, solutions-005 ]
    paths:
      - "bedtools_ng/**"
      - "data/**"
      - ".github/workflows/build-bedtools-ng.yml"
      - ".gitignore"
      - ".pyproject.yaml"
      - "setup.*"

# Define jobs
jobs:
  # Name first job
  build-bedtools-ng:
    # Pick the OS where the workflow will be run
    runs-on: ubuntu-latest

    # Define one of more steps
    steps:
      # Use an action to checkout the current repository
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git                \
                                  python3            \
                                  python3-pip        \
                                  python3-venv       \
                                  python3-setuptools

      - name: Install bedtools-ng
        run: pip install '.[all]'

      - name: Run unit tests
        run: pytest .

      - name: Run bedtools-ng
        run: |
          bedtools-ng --help
          bedtools-ng --version
          
          bedtools-ng data/chroms.bed \
                      data/grch38_transcripts.bed
